spring:
  datasource:
    url: jdbc:h2:~/test
  jpa:
    show-sql: true
    hibernate.ddl-auto: create
  application:
    name: iptreatment-offering-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
  h2: 
    console:
      enabled: true    

server:
  port: 8081
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://localhost:8761/eureka
  
  